Add download_pvolfiles
adokter/bioRad pull request #487
Opened 2021-12-21 22:23 UTC by Rafnuss

Addition of a function to download pvol file from AWS 

Some keys decision I made:
- Code follow  `download_vpfiles.R` as closely as possible
- Rely on the package [`aws.s3`](https://github.com/cloudyr/aws.s3). I've added it to `DESCRIPTION` as suggested. Note sure if that's correct usage. 
- The function does not accept multiple radar code. 
- `date_min` and `date_max` have to be set with hours and minutes.
- I've added a progess bar `setTxtProgressBar` from the `utils` pacakge. do you need `utils::setTxtProgressBar` ?. [`r-lib/progress`](https://github.com/r-lib/progress) would probably be nicer, but require a new package. What do you think?
- I wrote the test page that goes with it.

Related issues:  #41

2022-04-06 01:42 UTC, Rafnuss commented
Hi @adokter , there were indeed a few lines left from the download_vpts file. I am not sure how this happened. All checks have passed now. Hope this is good to go

2022-04-06 02:00 UTC, adokter commented
Thanks @Rafnuss, thanks almost ready, just a few small things, see above review

2022-04-06 02:02 UTC, adokter requested changes

2022-04-06 15:15 UTC, bart1 commented
> 
> Yes, good idea. I was just trying to follow [`download_vpfiles.R`](https://github.com/adokter/bioRad/blob/master/R/download_vpfiles.R). Should we change both at the same time then ?
> 
>     * Agree that standard date format should be accepted. I still haven't figure out what is the standard in R, seems rather unclear.

`POSIXct` is pretty much the de facto standard in R for timestamps, the `date` format for dates. `POSIXct` internally is as unix timestamp stored as a double. As a general comment for handling timestamps the `lubridate` package is really nice. It for example has an `%within%` function to test if a date is within an interval
 
>     * I am not convinced of the full day option. It's relatively easy for the user to specify both date. But if there is a consensus toward that standard, I can implement it.

It would make some operations easier like parallel operations e.g.:
```R
parallel::mclapply(as.Date("2016-1-1")+1:10, download_pvolfiles, radar='xxx')
```
Its not really crucial but I thought it might be an easy add

> 
>     * Often we only want the night data. In my Matlab code, I have a parameter that check this. Is there something easy/already exisiting in bioRad to do that?

The `bioRad::sunset` function identifies the right times. If the function would accept lubridate intervals something like this could work
```R
ints<-lubridate::interval(sunset(Sys.Date()+1:10,1,1), sunrise(Sys.Date()+2:11,1,1))
lapply(ints, download_pvolfiles, radar='xxx')
# or if a vector if ints could be fed this could work
download_pvolfiles(ints, radar='xxx')
```
> 
>     * I'll check about timezone. The data on aws is stored in UTC, so I guess we could have at timezone parameter. But coming back to your first point, I would almost be in favor to only accept standard date type which have timezone incorporated in them by default. Then we don't have to worry about that.
> 
`POSIXct` incorporates a timestamp and for that reason might be a good choice.

> 
> Let me know what you think and I can give it a go.

2022-04-06 22:01 UTC, Rafnuss commented on R/download_pvolfiles.R
> +  possible_radar <- c("KABR", "KABX", "KAKQ", "KAMA", "KAMX", "KAPX", "KARX",
Ok, suggesting to do that with a `trycatch`: 
https://github.com/adokter/bioRad/blob/06082eb39e4c271c965c50d16a4573a03f212c91/R/download_pvolfiles.R#L76-L85

2022-04-06 22:02 UTC, Rafnuss commented on R/download_pvolfiles.R
>      as.Date(substring(date_min, 1, 10), tz = NULL),
OK, https://github.com/adokter/bioRad/blob/06082eb39e4c271c965c50d16a4573a03f212c91/R/download_pvolfiles.R#L45-L46

2022-04-06 22:03 UTC, Rafnuss commented on R/download_pvolfiles.R
> +    pb <- txtProgressBar(min = 0, max = nrow(bucket_df), initial = 0, style = 3)
https://github.com/adokter/bioRad/blob/06082eb39e4c271c965c50d16a4573a03f212c91/R/download_pvolfiles.R#L123

2022-04-06 22:05 UTC, Rafnuss commented
Ok, I have done most of the suggestions with the exception of :
- Accepting full day download or date format (only`POSIXct`)
- Night/Day filtering
- parallelisation

2022-04-08 13:19 UTC, peterdesmet commented
Thanks for this @Rafnuss. Note that I will likely update `download_vpfiles.R` in the future, to download more convenient tabular files (https://github.com/enram/vpts-dp/issues/25) from the repository rather than the raw vp hdf5 files. I will then assess the start/end parameters too (and likely use posix).

2022-04-21 20:23 UTC, merged