Removed rgdal dependency
adokter/bioRad pull request #570
Opened 2023-05-17 04:35 UTC by iskandari

- Asserts that the output of `wgs_to_pro()j` and `proj_to_wgs()` are SpatialPoints objects and not SpatialPointsDataFrame objects; object type is not guaranteed by `spTransform`. 
 

> If `rgdal` is loaded, spTransform() converts the SpatialPoints object to a SpatialPointsDataFrame object, even if we call `sp::spTransform` specifically, R's method dispatch system will still use the `rgdal` version of the function *if* it's available in the namespace and the object being transformed is of a class that `rgdal` provides a method for.   We do not want to assume that `rgdal` is or is not loaded in the namespace, therefore, the output must be asserted. 

- Removed rgdal from NAMESPACE and DESCRIPTION files
- Checked that outputs match expected outputs for all function calls of `spTransform`

2023-05-17 05:59 UTC, bart1 commented on R/project_as_ppi.R
> +    browser()
I guess this should still be removed

2023-05-17 13:53 UTC, adokter commented
@iskandari unit tests require some updates, `test-integrate_to_ppi` and `test-project_as_ppi` use spTransform, which requires rgdal. spTransform should be replaced with st_transform from sf package

2023-05-17 14:51 UTC, bart1 commented
`withr` is nice for doing this kind of thing: https://withr.r-lib.org/reference/with_envvar.html

2023-05-17 15:01 UTC, bart1 commented
As `withr` is a dependency of `ggplot2` so we could add it as a temporary dependency until this is resolved, then something like this should work:
```r
withr::withr_envvar(list(sp_evolution_status=2), spTransfrom(....))
```

2023-05-17 18:30 UTC, bart1 commented
Nice idea to make a function out of it I would only suggest to not export it to prevent having to keep it around long term

2023-05-17 19:01 UTC, iskandari commented
> Nice idea to make a function (`spTransform2`) out of it I would only suggest to not export it to prevent having to keep it around long term

Yes that's the approach I took, thanks for the suggestion @bart1 !

2023-05-22 12:08 UTC, bart1 commented
I see the evolution status needs to be set before loading sp ( https://github.com/edzer/sp/blob/main/R/AAA.R ), I'm not sure how that works when importing a package, but that might complicate matters why the withr solution does not work

2023-05-25 01:52 UTC, iskandari commented
Behavior with regards to sp and rgdal is now the following:

On package load, evolution status is automatically set to 2 and user is notified (this will very soon be the default with sp):

```
> library(bioRad)
Welcome to bioRad version 0.7.0.9581
using vol2birdR version 1.0.0 (MistNet not installed)
Assigned sp_evolution_status to 2
```

bioRad functions that use rgdal-based sp functions run without errors, whether or not rgdal is installed on the system.  Currently, sp business as usual will use rgdal if it is installed **even if it is not loaded**.  That is handled by checking the output of spTransform() and if necessary converting back to SpatialPoints

```
> sp::get_evolution_status()
[1] 2
> project_as_ppi(my_scan)
               Plan position indicator (class ppi)

  parameters:  DBZH VRADH RHOHV ZDR PHIDP 
        dims:  201 x 201 pixels 
```

If evolution status is set back to 0 *and* rgdal is not installed, bioRad functions that use rgdal-based sp functions throw an error that is handled with a message to the user to reset the evolution status parameter:

```
> sp::set_evolution_status(0L)
[1] 0
> project_as_ppi(my_scan)
Error: spTransform failed. Try resetting sp_evolution_status: sp::set_evolution_status(2L)
> sp::set_evolution_status(2L)
[1] 2
> project_as_ppi(my_scan)
               Plan position indicator (class ppi)

  parameters:  DBZH VRADH RHOHV ZDR PHIDP 
        dims:  201 x 201 pixels
```

2023-05-30 16:15 UTC, adokter requested changes

2023-05-30 16:15 UTC, adokter commented on R/hooks.R
> +  if (requireNamespace("sp", quietly = TRUE)) {
this statement is already present in the 4 lines above it

2023-05-30 16:15 UTC, adokter commented on R/hooks.R
> +  if (requireNamespace("sp", quietly = TRUE)) {
I noticed in the readme you still ask users to set the sp_evolution_status manually as well, is that still necessary or does this statement take care of it already?

2023-05-30 17:51 UTC, closed without merging