Move helper functions to utils.R
adokter/bioRad pull request #587
Opened 2023-05-24 14:03 UTC by PietrH

2023-05-24 14:20 UTC, PietrH commented
ready for review

2023-05-25 17:00 UTC, iskandari requested changes

2023-05-26 07:14 UTC, PietrH commented on R/utils.R
> +}
While I agree that refactoring with `lubridate` is a good idea to increase robustness, I believe this should be done in a seperate PR. In this change I only moved existing code. 

I think we should make an issue for refactoring efforts and implement it separately to make the changes easier to track.

2023-05-26 19:46 UTC, iskandari commented on R/utils.R
> +}
Makes sense!

2023-05-26 19:46 UTC, iskandari approved these changes

2023-05-26 20:35 UTC, merged